name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build with Next.js
        run: npm run build -- --no-lint
        # Next.js 13+ uses 'output: export' in next.config.ts to generate static files

      - name: Fix 404.html
        run: |
          if [ -d "out/404" ]; then
            cp out/404/index.html out/404.html
          elif [ -f "out/404.html" ]; then
            echo "404.html already exists"
          else
            # Create a basic 404 page if none exists
            echo '<html><head><meta http-equiv="refresh" content="0;url=/wutuo/"></head><body>Page not found. Redirecting to home...</body></html>' > out/404.html
          fi

      - name: Verify build artifacts
        run: |
          echo "Checking build artifacts..."
          ls -la out/
          echo "Checking for critical files..."
          if [ -f "out/index.html" ]; then
            echo "✅ index.html exists"
          else
            echo "❌ index.html is missing"
            exit 1
          fi
          if [ -f "out/404.html" ]; then
            echo "✅ 404.html exists"
          else
            echo "❌ 404.html is missing"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 